supply:
  saltKey: wxs-wsx-honor
  des3:
    license: d5e0c4e1-c974-483e-934e-49390ce4d547
  rsa:
    publicPem: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCcDPb4tHudrDcDx/p4H+GiLMaLIc+3yMoyLkISh96Yph5JxkSpPxlH1+DKm36wo+kKBcKLU8Swja6NJ0lIVhAs1qOJMMPq7g0tgrxGIGb2U7UMsMCl+76KVY5qfPpBeINqiWRWnuCIXcl2qRvH6R4R0QFRUPKygZAQt/tkHERo3wIDAQAB
    privatePem: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAJwM9vi0e52sNwPH+ngf4aIsxoshz7fIyjIuQhKH3pimHknGRKk/GUfX4MqbfrCj6QoFwotTxLCNro0nSUhWECzWo4kww+ruDS2CvEYgZvZTtQywwKX7vopVjmp8+kF4g2qJZFae4IhdyXapG8fpHhHRAVFQ8rKBkBC3+2QcRGjfAgMBAAECgYEAi6vG+X+BDPTxIL9C3XWbnG37HtiadGKRJyzkEnXttC8q+Nku51UEqZr9Jhra3/s1P7U8FTxa1bNaQhihrM7rFe8no18GlsC92C76zoY+Q7kZzXWllZb12ySQsNK93Qg81dh/aNOTwISQkLz4M6MKZKCXqJfzMnlWO7V7oWnNsWECQQDdtDFTS2ymRoT7rV0hSP/KDM4WstxybrjXDenTCOL5TGpu1XTRj6tI/Rfmhxpi5Z/Pa1RNoqMqB1+B3UOqwp3JAkEAtDDOHeV4aLKR4dBCOVv6yFbN+sMDU2gXjnVgWC3tyxWGqE30Bd/av9RrwknjjHYWgBivRPPSx+TGJMtbzNIFZwJBAJ6PG+PdgpQcxUkWQQ/oHIBNzirvurfgtjOgEMXMikAPxeMEqKqj3LWzxR8rKtTmMvhuY3muwpDxev3u2FFNJPkCQCZfDkWHjDCfdjlkI/YbBDiNY6e2x4qHbBzGGhItFapdlyNYFlL57JdVIO1q1q4ep4P3vbstQQGYUimbtJzVTJkCQQCr+n7BXKj38ndXE5hmz83bq8Qj5x0SdXFaOnSGHWzKRtZDl1tOBmlYMqAsH/iWnYZgNWouIXVKC0PrYphwHjko


